### subscribe to eth
POST http://localhost:8090/api/v1/marketdata/subscribe/XETUSD

### subscribe to btc
POST http://localhost:8090/api/v1/marketdata/subscribe/XBTUSD

### unsubscribe to eth
POST http://localhost:8090/api/v1/marketdata/subscribe/XETUSD

### unsubscribe to btc
POST http://localhost:8090/api/v1/marketdata/unsubscribe/XBTUSD